### ISSUE TITLE
Running code in AWS or any remote machine other than localhost

### ISSUE THREAD

**Issue by nicefella** [yianni-ververis/CIO#2]
Hi,

Could you tell me what the requirements and configs should be when deploying this site on a remote machine?
Applying host and scriptUrl parameters to http://{REMOTE MACHINE NAME}:3000 doesn't seem to work.
Thanks and best regards

**Comment by yianni-ververis** [comment]
I use https://localhost:3000 without issues

"host": "sense-demo-staging.qlik.com",
"port": 443,
"id": "",
"scriptsUrl": "https://localhost:3000/",
"baseUrl": "https://sense-demo-staging.qlik.com/resources"

**Comment by nicefella** [comment]
Thanks for prompt answer,
But there are several sections in config file such as local, local2, staging, production.
Which one are you using? 
And how are you accessing the site? Like https://sense-demo-staging.qlik.com:3000 ?

Our config is pretty much same except we are using port 80 and http://localhost:3000.
Do you think that it does matter?

Thanks

**Comment by nicefella** [comment]
To be more clear,

I want to deploy this site code (node project) on a remote machine.  
So I need to figure it out how i can access it rather than typing localhost:3000.
Should Qlik Sense Server and this project be on different machines for example?
We opened an EC2 instance on AWS, installed a Qlik Sense environment on it and copied / started running this node project on it as well.
But accessing it like https://ec2-34-215-208-23.us-west-2.compute.amazonaws.com:3000/ or http://ec2-34-215-208-23.us-west-2.compute.amazonaws.com:3000/ doesn't show any page.

**Comment by yianni-ververis** [comment]
Yes I am sorry for closing it early. Put the nodejs code on your local machine. Once you "gulp", this will create the files in the "dist" folder and will a spin a local server for testing at "localhost:3000". These files are created for local testing only, using the settings from project.json->local2.

Once you are ready to deploy to production, put your settings in project.json->production object. This will be as host, the dns of your EC2 instance with the port, the app id, virtual proxy and the baseUrl for the resource files. Then what we do, is upload the entire "dist" folder to an S3 backet. That would be the url for "scriptUrl".

**Comment by nicefella** [comment]
I noticed that I forgot to inform you. Sorry and thank you. 
It worked as you instructed. The only difference is that we host dist files on IIS rather than an S3 bucket.
