### ISSUE TITLE
Refresh kpiexpressions on every click?

### ISSUE THREAD

**Issue by rvaheldendaten** [yianni-ververis/CIO#4]
Hi!

Not really an issue, but from my tests it seems that the <kpi>-expressions are only updated once on "Pageload". 

![kpisnureinmalaktualisiert](https://user-images.githubusercontent.com/11175181/33481698-fa043850-d695-11e7-9274-a7ece7462a6b.png)

Can you point me to the place in the code, where I can execute the kpi-expressions on every click?

Thx,
Roland

**Comment by yianni-ververis** [comment]
Its by default. Change the kpi directive from using promises to callbacks
https://github.com/yianni-ververis/CIO/blob/master/src/js/directives/kpi/kpi.js

from
api.getHyperCubeQ([], [newValue]).then((data) => {
    scope.data = data[0][0];
})

to
api.getHyperCube([], [newValue], (data) => {
    scope.data = data[0][0];
})

**Comment by rvaheldendaten** [comment]
Great, works :-)
